version: '3.8'

services:
  # Portainer : Pour gérer tes containers via http://localhost:9443
  #GreenHouseAdmin2026!
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data

  # Mosquitto : Le broker MQTT pour tes futurs ESP32
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data

  # Redpanda : Kafka ultra-léger (C++) sans Zookeeper
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.2.1
    container_name: redpanda
    command:
      - redpanda start
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 0
      - --check=false
      - --kafka-addr PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://localhost:9092
    ports:
      - "9092:9092"

  # PostgreSQL : Stockage long terme pour tes analyses
  postgres:
    image: postgres:15
    container_name: greenhouse_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: greenhouse
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    # L'outil de management visuel
  pgadmin:
    image: dpage/pgadmin4
    container_name: greenhouse-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

  minio_storage:
    image: minio/minio
    container_name: minio_storage
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    volumes:
      - ./minio_data:/data
    # Cette commande fait tout en une seule fois
    command: >
      sh -c "minio server /data --console-address ':9001' & 
             sleep 5; 
             mc alias set local http://localhost:9000 admin password;
             mc mb local/images || true;
             mc anonymous set download local/images;
             wait"

  # Grafana : Ton tableau de bord (http://localhost:3000)
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - postgres