# Ce fichier gère UNIQUEMENT ton code Python (FastAPI, Spark, Bridge).
# Il inclut automatiquement l'infrastructure avant de démarrer.

include:
  - docker-compose.infra.yml

services:
  # ========================================================
  # TES SERVICES PYTHON (MICRO-SERVICES)
  # ========================================================

  # 1. L'API Backend (FastAPI)
  fastapi_backend:
    build: .
    container_name: ingestion_image
    # L'astuce "python -m" garantit qu'on trouve le module même si le PATH système est mal configuré
    command: python -m uvicorn apps.ingestion_image.image_main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_started
      redpanda:
        condition: service_started
      minio_storage:
        condition: service_started
      kafka_setup:
        condition: service_completed_successfully

  # 2. Le Bridge MQTT -> Kafka
  mqtt_bridge:
    build: .
    container_name: mqtt_bridge
    environment:
      - PYTHONPATH=/app
    # On lance un simple script Python
    command: python apps/bridge/bridge.py
    depends_on:
      mosquitto:
        condition: service_started
      redpanda:
        condition: service_started
      kafka_setup:
        condition: service_completed_successfully

  # 3. Le processeur Spark Télémétrie
  spark_telemetry:
    build: .
    container_name: spark_telemetry
    environment:
      - PYTHONPATH=/app
    # Plus besoin de spark-submit, PySpark gère tout en interne !
    command: python apps/spark_processor/telemetry_processor.py
    depends_on:
      postgres:
        condition: service_started
      redpanda:
        condition: service_started
      kafka_setup:
        condition: service_completed_successfully

  # 4. Le processeur Spark Images
  spark_images:
    build: .
    container_name: spark_images
    environment:
      - PYTHONPATH=/app
    command: python apps/spark_processor/image_processor.py
    depends_on:
      postgres:
        condition: service_started
      redpanda:
        condition: service_started
      minio_storage:
        condition: service_started
      kafka_setup:
        condition: service_completed_successfully

  # 5. Le processeur Spark Météo
  spark_weather:
    build: .
    container_name: spark_weather
    environment:
      - PYTHONPATH=/app
    command: python apps/spark_processor/processor.py
    depends_on:
      postgres:
        condition: service_started
      redpanda:
        condition: service_started
      kafka_setup:
        condition: service_completed_successfully