# Ce fichier contient UNIQUEMENT les services "lourds" (Bases de données, Brokers)
# Il peut être lancé seul pour le développement local.

services:
  # Portainer : Pour gérer tes containers via une belle interface web
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data

  # Mosquitto : Le système nerveux central (MQTT)
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data

  # PostgreSQL + TimescaleDB : La mémoire à long terme et les configurations
  postgres:
    image: timescale/timescaledb:latest-pg15
    container_name: greenhouse_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: greenhouse
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  # pgAdmin : Pour fouiller dans ta base de données à la souris
  pgadmin:
    image: dpage/pgadmin4
    container_name: greenhouse-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      # Désactive la demande de mot de passe maître au lancement
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
      # Force le mode serveur pour charger les JSON
      PGADMIN_CONFIG_SERVER_MODE: 'True'
    volumes:
      # Utilise ./ pour être sûr du chemin relatif sous Windows
      - ./servers.json:/pgadmin4/servers.json
      # On ajoute un volume nommé pour que tes préférences restent
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8080:80"
    depends_on:
      - postgres

  # MinIO : Le coffre-fort pour tes images et vidéos
  minio-storage:
    image: minio/minio
    container_name: minio-storage
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
      MINIO_SERVER_URL: "http://127.0.0.1:9000"

    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"

  # Redis : Le broker ultra-léger pour les tâches Celery (et le cache Temps Réel)
  redis:
    image: redis:7-alpine
    container_name: redis_broker
    restart: always
    ports:
      - "6379:6379"
    # Persistance légère pour ne pas perdre les tâches si le container crash
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - ./redis_data:/data

volumes:
  pgadmin_data: