# Ce fichier contient UNIQUEMENT les services "lourds" (Bases de données, Brokers)
# Il peut être lancé seul pour le développement local.

services:
  # Portainer : Pour gérer tes containers via une belle interface web -> deleted

  # Mosquitto : Le système nerveux central (MQTT)
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data

  # PostgreSQL + TimescaleDB : La mémoire à long terme et les configurations
  postgres:
    image: timescale/timescaledb:latest-pg15
    container_name: greenhouse_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: greenhouse
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  # pgAdmin : Pour fouiller dans ta base de données à la souris -> la console suffit
  # MinIO : Le coffre-fort pour tes images et vidéos
  minio-storage:
    image: minio/minio
    container_name: minio-storage
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
      MINIO_SERVER_URL: "http://127.0.0.1:9000"

    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"

  # Redis : Le broker ultra-léger pour les tâches Celery (et le cache Temps Réel)
  redis:
    image: redis:7-alpine
    container_name: redis_broker
    restart: always
    ports:
      - "6379:6379"
    # Persistance légère pour ne pas perdre les tâches si le container crash
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - ./redis_data:/data

  ngrok:
    image: ngrok/ngrok:latest
    container_name: hydro-ngrok
    restart: unless-stopped
    command:
      - "http"
      - "hydro_frontend:80" # ⚠️ Remplace "frontend" par le vrai nom de ton service React dans le docker-compose
      - "--domain=clump-scavenger-stucco.ngrok-free.dev" # ex: renard-agile-84.ngrok-free.app
      - "--oauth=google" # <-- Active le portail Google
      - "--oauth-allow-email=jules.goueffon89@gmail.com"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}





volumes:
  pgadmin_data: