# docker-compose.prod.yml
include:
  - docker-compose.app.yml # Assure-toi que c'est bien le nom de ton fichier de base

services:
  # ========================================================
  # LE BOUCLIER NGROK (Authentification Google Edge)
  # ========================================================
  ngrok:
    image: ngrok/ngrok:latest
    container_name: hydro_ngrok
    restart: unless-stopped
    command:
      - "http"
      # ⚠️ REMPLACE "frontend:80" par le nom EXACT de ton service Nginx dans ton docker-compose.app.yml
      - "hydro_frontend:80"
      - "--domain=clump-scavenger-stucco.ngrok-free.dev"
      - "--basic-auth=Maou:@Maou_la_raleuse.2202"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}