apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: greenhouse_db:5432
    database: greenhouse
    user: admin
    secureJsonData:
      password: password
    jsonData:
      sslmode: 'disable'
      postgresVersion: 15
      timescaledb: true