server {
    listen 80;
    server_name _;

        # 2. On redirige tout ce qui commence par /api vers FastAPI
    location /api/ {
        # ⚠️ REMPLACE "backend" PAR LE NOM DE TON SERVICE FASTAPI DANS LE DOCKER-COMPOSE
        proxy_pass http://fastapi_backend:8000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 1. On sert l'application React
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Crucial pour React Router (évite les erreurs 404 au rechargement)
        try_files $uri $uri/ /index.html;
    }


}